### ISSUE TITLE
Location of read length, single end vs paired, stranded, etc... ?

### ISSUE THREAD

**Issue by radlinsky** [ENCODE-DCC/submission_sample_scripts#1]
I am using your example code to download ENCODE meta data, but I can't seem to find meta data pertaining to the library prep? I.e. read lengths, single/paired ended, and whether or not the library prep was stranded. Is that kind of meta data available to download? If so, how do I get it ? Thanks.. -Radlinsky

**Comment by estherc** [comment]
Hi Radlinsky,

General library prep metadata can be found in the library object (see https://www.encodeproject.org/profiles/library.json for the captured properties), which can be accessed via experiment.replicates.library for each experiment (ENCSR) accession of interest. The library.strand_specificity boolean value indicates whether the library prep was stranded or not. Information about read lengths, single or paired-endedness can be found in the file object (see https://www.encodeproject.org/profiles/file.json), which can be accessed via experiment.files.read_length and experiment.files.run_type for each experiment of interest.

Alternatively, if you have a list of experiments you're interested in, you can select them on the ENCODE portal (https://www.encodeproject.org), and take advantage of the batch download feature by clicking the "Download" button at the top of the list view. A file called files.txt will download to your computer containing a list of download paths for all of the data files in your list along with a file called metadata.tsv that will contain select metadata. You can choose to just download that metadata file if you like with curl. Read more about the batch download feature on the portal: https://www.encodeproject.org/help/batch-download/

If you have further questions or need more clarification, please contact us at encode-help[at]lists.stanford.edu

Cheers,
Esther

**Comment by radlinsky** [comment]
Thanks Esther,

I'll try and get the meta info from the library object as you suggested.

Unfortunately, the metadata.tsv file does not include information about the read lengths, single vs paired ended-ness, and whether or not the library prep was stranded. To be perfectly frank, I think there is a bug in the encode website somewhere because the metadata.tsv table has column names such as "Read length" and "Paired end," but the rows are all blank.. 

I'll email encode-help[at]lists.stanford.edu regarding this...

Best,

- Radlinsky
